### ISSUE TITLE
Stats bayésiennes : graphiques contre-intuitifs

### ISSUE THREAD

**Issue by Aluriak** [dridk/blog#13]
Actuellement, les patient sont représentés par des points, dont la couleur dépend s'ils sont malades ou pas.
Le fait qu'il aient été testé est représenté par… Ah non, pardon : ils ont tous été testés, mais seuls ceux inclus dans un cercle en pointillés ont été testés positifs.

C'est contre intuitifs : pourquoi les patients testés positifs sont tous à côté ?
L'inverse me semble plus naturel : les patients malades sont rassemblés dans un cercle en pointillé, et la couleur d'un patient dépend de son résultat au test.

Ça améliorerais beaucoup la lisibilité des graphiques.

**Comment by dridk** [comment]
Imagine qu'on mette les patients malades dans une prison si ils sont testé positif. Je trouve ça plus logique.  

Le fait d'être malade ou non, blond ou brun est fixé chez l'individu.  Seul le test varie.  Donc je trouve ton schéma plutôt contre intuitif.

**Comment by Aluriak** [comment]
C'est marrant, j'aurais dis l'inverse justement.

Une autre manière de voire la chose, c'est de regarder le problème avec l'œil d'un humain :
- à la base, tous les patients sont dans un état inconnu
- on leur fait un test
- on en déduit un clustering (malade/non malade), potientiellement avec des faux, positifs ou négatifs
- magie : l'état réel des patients est alors révélé : on peut alors calculer l'efficacité du test

Si on change de test, on change juste la couleur des nœuds, et il suffit de compter les couleurs dans la partie cerclée pour avoir les résultats du test.

L'approche inverse, actuellement proposée par les graphiques, suggère l'omniscience : on sait lesquels sont malades, et le test est un truc fait a posteriori.

C'est une proposition hein. Clôt l'issue si elle est mauvaise. D'autant que ça change pas grand chose. Je (en tant qu'instance de la classe Humain) trouve juste ça plus lisible dans l'autre sens.
