### ISSUE TITLE
SnpSift filter

### ISSUE THREAD

**Issue by GitJuju** [dridk/blog#27]
Bonjour
Cette commande semble enlever ('filter out') le contenu du fichier SRR13182925.ann.vcf.
SnpSift filter "(exists ANN[0].HGVS_P)" > SRR13182925.ann.vcf
Elle se trouve dans ce fichier: blog/content/covid_ngs.md
Il n'y en a peut être pas besoin. Cette commande seule marche bien: 
SnpSift extractFields - "ANN[0].HGVS_P" "ANN[0].GENE"
Julien

**Comment by dridk** [comment]
Ok ! Tu as besoin de ce champs "filter out" dans ton projet ?

**Comment by GitJuju** [comment]
non je passe à travers le billet pour essayer de le reproduire et je constate que chez moi ca ne fonctionne pas de la même façon. j'ai utilisé cette commande pour pouvoir voir les 2 colonnes:
SnpSift extractFields - "ANN[0].HGVS_P" "ANN[0].GENE" < SRR13182925.ann.vcf

**Comment by GitJuju** [comment]
c'est juste un commentaire pas un véritable problème. L'issue peut être fermée.

**Comment by dridk** [comment]
Ok, je vais voir de mon coté ! Merci en tt cas! J'espère que tu as réussi à reproduire le reste .

**Comment by GitJuju** [comment]
Oui oui c'est vraiment bien
merci
